# Generated by Django 3.1.13 on 2021-08-11 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aadiscordbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message', models.BigIntegerField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=1000)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('author', models.PositiveBigIntegerField()),
                ('author_nick', models.CharField(blank=True, max_length=50, null=True)),
                ('reference', models.CharField(help_text='Nickname for this quote', max_length=100)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aadiscordbot.channels')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aadiscordbot.servers')),
            ],
        ),
    ]
