# Generated by Django 3.1.1 on 2020-09-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aadiscordbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channels',
            name='channel_id',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servers',
            name='server_id',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False),
        ),
    ]
