# Generated by Django 4.2.9 on 2024-03-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aadiscordbot', '0011_alter_ticketgroups_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='welcomemessage',
            name='guild_id',
            field=models.BigIntegerField(default='430608269988593664'),
        ),
    ]
