# Generated by Django 4.2.9 on 2024-03-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aadiscordbot', '0012_welcomemessage_guild_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodbyemessage',
            name='guild_id',
            field=models.BigIntegerField(default='430608269988593664'),
        ),
    ]
