# Generated by Django 4.2.16 on 2024-10-12 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aadiscordbot', '0015_ticketgroups_ticket_channels'),
    ]

    operations = [
        migrations.AddField(
            model_name='authbotconfiguration',
            name='admin_user_ids',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ticketgroups',
            name='ticket_channel',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aadiscordbot.channels'),
        ),
    ]
