# Generated by Django 5.2.12 on 2026-06-25 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aadiscordbot', '0016_authbotconfiguration_admin_user_ids_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authbotconfiguration',
            options={'verbose_name': 'AuthBot Configuration'},
        ),
        migrations.AddField(
            model_name='authbotconfiguration',
            name='honeypot_channels',
            field=models.ManyToManyField(
                to='aadiscordbot.channels', verbose_name=''),
        ),
    ]
