# Generated by Django 5.2.17 on 2026-08-20 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aadiscordbot", "0017_alter_authbotconfiguration_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="authbotconfiguration",
            name="honeypot_reports_channel",
            field=models.ForeignKey(
                blank=True,
                help_text="The channel where reports of users banned by the honeypot feature will be sent.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="honeypot_reports_channel",
                to="aadiscordbot.channels",
                verbose_name="Honeypot Reports Channel",
            ),
        ),
    ]
